name: CI Work Flow

on:
  push:
  pull_request:

jobs:
  linting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_version: ['3.9', '3.8']
      fail-fast: false
      max-parallel: 2

    steps:
      - name: code checkout
        uses: actions/checkout@v3
    
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: install flake8
        run: |
          python -m pip install --upgrade pip 
          pip install flake8

      - name: run flake8
        run: |
          flake8 app.py
    